### ISSUE TITLE
Nothing output but 'Welcome to TurnVoice!'

### ISSUE THREAD

**Issue by linmingren** [KoljaB/TurnVoice#4]
I installed turnvoice on an Ubuntu machine with Python version 3.11.8. The installation went perfectly, but then I tried a few commands, such as "turnvoice -i test.mp4 -l zh-CN -v daisy -dbg" . However, all commands just printed out "Welcome to TurnVoice!" without any errors or useful information.

**Comment by KoljaB** [comment]
Appears related to the [coqui engine](https://github.com/KoljaB/TurnVoice/discussions/1#discussioncomment-8397527). TurnVoice is in early pre-alpha stage, as highlighted in the [project documentation](https://github.com/KoljaB/TurnVoice?tab=readme-ov-file#user-content-fn-1-295976cbbadf9b749dd0e4ab324374ab). In this stage of development typically not all features are polished, sometimes in areas like error handling.

It is complex, integrating various advanced AI components. Such projects, especially in early development stages and on platforms different from the original testing environment (Python 3.11.4 on Windows 10), often necessitates additional time for troubleshooting and debugging. I'm unable to provide detailed advice at this moment, as my current commitments prevent me from dedicating further time to this project.

**Comment by linmingren** [comment]
It looks like I didn't install spleeter library and TurnVoice just quit silently.

**Comment by dorbodwolf** [comment]
> It looks like I didn't install spleeter library and TurnVoice just quit silently.

sure, the problem is here:
```   
# turnvoice/core/prepare.py
if not verify_install("spleeter", "rubberband"):
        return
```
