### ISSUE TITLE
Get's stuck on Refine

### ISSUE THREAD

**Issue by yarodevuci** [KoljaB/TurnVoice#7]
Input #0, wav, from '1234.wav':
  Metadata:
    encoder         : Lavf58.29.100
  Duration: 00:00:13.49, bitrate: 1411 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
Please use -b:a or -b:v, -b is ambiguous
[out#0/mp3 @ 000002b8fd386500] Codec AVOption b (set bitrate (in bits/s)) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
Output #0, mp3, to 'downloads\1234.mp3':
  Metadata:
    TSSE            : Lavf60.4.100
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p
    Metadata:
      encoder         : Lavc60.7.100 libmp3lame
size=     212kB time=00:00:13.48 bitrate= 128.6kbits/s speed= 138x
video:0kB audio:211kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.116396%
Splitting audio downloads\1234.mp3 into accompaniment and  vocals (downloads\htdemucs_ft\1234/vocals.wav) using demucs.
Selected model is a bag of 4 models. You will see that many progress bars per track.
Separated tracks will be stored in G:\Local_API\TelegramBots\InstaAnalytics\downloads\htdemucs_ft
Separating track downloads\1234.mp3
100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:04<00:00,  3.95seconds/s]
100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:03<00:00,  4.70seconds/s]
100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:03<00:00,  4.75seconds/s]
100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:03<00:00,  4.68seconds/s]
Vocals and accompaniment files exist, returning paths: downloads\htdemucs_ft\1234/vocals.wav and downloads\htdemucs_ft\1234/no_vocals.wav
[20.6s] splitting finished, vocal path is downloads\htdemucs_ft\1234/vocals.wav...
[20.6s] early start synthesis engine (grab vram)...
No engine specified for voice 1. Using first/default engine coqui
Switching engine to coqui, voice daisy
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.36k/4.36k [00:00<?, ?iB/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.86G/1.86G [00:18<00:00, 99.8MiB/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335k/335k [00:00<00:00, 2.35MiB/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.75M/7.75M [00:00<00:00, 22.5MiB/s]
 > Using model: xtts
Predicted silence(s) with VAD.       cting silences(s) with VAD...
Detected language: english
Transcribe: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13.49/13.49 [01:35<00:00,  7.08s/sec]
Refine:   0%|                                                                                                                                                                                | 0/13.49 [00:00<?, ?sec/s]

**Comment by yarodevuci** [comment]
turnvoice .\1234.mp4 -e coqui
Welcome to TurnVoice!
input parameters:
- video: .\1234.mp4
- translation language:
- input video language:
- download directory: downloads
- synthesis directory: synthesis
- extract: False
- voices: None
- output video: final_cut.mp4
- clean audio: False
- start: None
- end: None
- analysis: False
- speaker number:
- num speakers: 0
- min speakers: 0
- max speakers: 0
- time files: None
- prompt: None- debug: False
- prepare: False
- render: None
- use faster: False
- model: large-v2

checking if url is youtube url...
extracting from local file...
Files '.\1234.wav' and '.\1234_muted.mp4' already exist, skipping extraction
file '1234.wav' already exists, skipping renaming...
[0.3s] splitting audio...
Checking if vocals and accompaniment files exist: downloads\htdemucs_ft\1234/vocals.wav and downloads\htdemucs_ft\1234/no_vocals.wav
Vocals and accompaniment files exist, skipping separation and returning paths: downloads\htdemucs_ft\1234/vocals.wav and downloads\htdemucs_ft\1234/no_vocals.wav
[0.3s] splitting finished, vocal path is downloads\htdemucs_ft\1234/vocals.wav...
[0.3s] early start synthesis engine (grab vram)...
No engine specified for voice 1. Using first/default engine coqui
Switching engine to coqui, voice male.wav
 > Using model: xtts
Predicted silence(s) with VAD.       cting silences(s) with VAD...
Transcribe:   0%|                                                                                                                                                                            | 0/13.49 [00:00<?, ?sec/s]

**Comment by yarodevuci** [comment]
no matter what I pick it gets stuck

**Comment by yarodevuci** [comment]
@KoljaB any ideas? Thanks

**Comment by KoljaB** [comment]
Seems to be stuck in stable_whispers refine method, no clue why.
Please remove [this part](https://github.com/KoljaB/TurnVoice/blob/main/turnvoice/core/transcribe.py#L229-L233) from the transcribe.py file in the source and try again.
